# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a0c8fa0498a84bc36523fb7c26c35b0b518a678953fd246a72f564f5a0df67070866d77a8ecf519bd71cfb68070cc4ab73b90e8f38856dd974105b77c0d0b8b

test:
  secret_key_base: f74a1606c859c07f411c906b2bd7e5f2bb578474a0ea283950b463532f27c7b6fec496a54681baa5ced55f3ffef01898faf161ec4bffffe7ecd035ba37b68616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
